with-expecter: true
dir: mocks
outpkg: mocks
filename: "{{.InterfaceName | snakecase}}.go"
packages:
  go.fork.vn/cache:
    interfaces:
      Manager:
        config:
          recursive: true
      ServiceProvider:
        config:
          recursive: true
  go.fork.vn/cache/driver:
    interfaces:
      Driver:
        config:
          recursive: true
      RedisDriver:
        config:
          recursive: true
all: false
